project_name: test-goreleaser

before:
  hooks:
    - go mod tidy

builds:
  - id: gttest
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    binary: gttest
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    # includes czdaemon, czctl and czsupervisor binaries on the same tar.gz
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: gtrrz-victor
      name: homebrew-test-goreleaser
      branch: main
      token: "{{ .Env.GITHUB_PERSONAL_AUTH_TOKEN }}"
    description: Testing gorelaser.
    download_strategy: CurlDownloadStrategy
    url_template: "https://releases.codezero.io/{{ .Tag }}/headless-{{ .Os }}-{{ .Arch }}.tgz"
    homepage: https://??.io/
    install: |
      bin.install "czctl"
      bin.install "czdaemon"
      bin.install "czsupervisor"
