# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestGoreleaser < Formula
  desc "Testing gorelaser."
  homepage "https://??.io/"
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/v0.0.3/test-goreleaser-0.0.3-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "fdfb4f25bb7bd09b7fe0a4b7b0e49ffd987baa298e242508bbd5506f658d8ce2"

      def install
        bin.install "test"
      end
    end
    on_arm do
      url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/v0.0.3/test-goreleaser-0.0.3-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4b533c73b7c28e555cedbe2a80be713e3d95461fb26499ab21b3921dee348bc9"

      def install
        bin.install "test"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/v0.0.3/test-goreleaser-0.0.3-linux-amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "e511922c7882c3fc75f9281ecab2852696a78fc542d9afee2b918541fb7b8809"

        def install
          bin.install "test"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/v0.0.3/test-goreleaser-0.0.3-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "abc1cf8966d4fc803351ba94df5c4b5840c9ba257009013251f8f4a6a63c0efa"

        def install
          bin.install "test"
        end
      end
    end
  end

  test do
    system "#{bin}/test"
  end
end
