# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestGoreleaser < Formula
  desc "Testing gorelaser."
  homepage "https://??.io/"
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/v0.0.4/test-goreleaser-0.0.4-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f5ee8f4c6eb02b33e5d23e23d5155a5761f1edff6104710fab9d90df5e96e4c7"

      def install
        bin.install "test"
      end
    end
    on_arm do
      url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/v0.0.4/test-goreleaser-0.0.4-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "200c436cc858aa6f10195d44c0fe3cd12db714674a39ed5fac4b8c521bea5829"

      def install
        bin.install "test"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/v0.0.4/test-goreleaser-0.0.4-linux-amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "524e6b5a4c29dabd16644452648c07f548f80afc8ba7638e0159e447c7ace2de"

        def install
          bin.install "test"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gtrrz-victor/test-goreleaser/releases/download/v0.0.4/test-goreleaser-0.0.4-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "a46b9d43bc9c38c87f387bf5b3de74282610c8f1ab1dac1bffab4877baf2deb5"

        def install
          bin.install "test"
        end
      end
    end
  end

  test do
    system "#{bin}/test"
  end
end
