name: Build Binaries (Snapshot)

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: "1.22"
      CHOCOLATEY_VERSION: 2.2.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Create release
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --snapshot --timeout=90m -f .goreleaser-snap.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: binaries

          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: dist/*

          # Duration after which artifact will expire in days. 0 means using default retention.
          # Minimum 1 day.
          # Maximum 90 days unless changed from the repository settings page.
          # Optional. Defaults to repository settings.
          retention-days: 1
